    
- hosts: localhost
  tasks:
  - name: Touch /tmp/foo.tmp file
    file:
      path: /tmp/foo.tmp
      state: touch
      mode: u+rw,g-wx,o-rwx

  - name: Delete the /tmp/foo.tmp file
    file:
      path: /tmp/foo.tmp
      state: absent
    
